### ISSUE TITLE
Add an ability to deploy on k8s 1.16+

### ISSUE THREAD

**Issue by vterdunov** [kremers/charts-vmware-exporter#2]
here are changes in k8s api https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by kremers** [comment]
Have you tried installing on k8s 1.16+ and there are pending issues?
As far as I see it shouldn't have implications on the chart

**Comment by vterdunov** [comment]
I tried before created the issue:
e.g
https://github.com/kremers/charts-vmware-exporter/blob/242aa07a49ecd6ab6a72a548d196af64d2434cc0/templates/deployment.yaml#L1
Won't work. According the vlog post:
```
Deployment in the extensions/v1beta1, apps/v1beta1, and apps/v1beta2 API versions is no longer served
```

**Comment by kremers** [comment]
can you please test v2 of the chart?

**Comment by an-sy** [comment]
👌it works, tested with k8s 1.17

**Comment by vterdunov** [comment]
Unfortunately don't have a possibility to check the new version. Looks like @an-sy test it and I guess we can close it.
