### ISSUE TITLE
Looks like the service.labels values isn't actually in the template for the service.

### ISSUE THREAD

**Issue by yokhahn** [kremers/charts-vmware-exporter#5]
Looks like the service.labels values isn't actually in the template for the service.

**Comment by kremers** [comment]
You are right, you might contribute a pull request?

**Comment by daveoy** [comment]
#12  should fix this @kremers  @yokhahn

**Comment by kremers** [comment]
I'll see :)

**Comment by kremers** [comment]
merged and released new chart version
